In [1]:
from torchmeta.toy import Sinusoid

In [2]:
from datasets import KnobsDataset
from torch.utils.data import  DataLoader
from maml.utils import ToTensor1D


ModuleNotFoundError: No module named 'datasets'

In [ ]:
from torchmeta.utils.data import BatchMetaDataLoader
from torch.utils.data import  DataLoader
from torchmeta.transforms import ClassSplitter

In [ ]:
transform = ToTensor1D()
dataset_transform = ClassSplitter(shuffle=True,
                                      num_train_per_class=5,
                                      num_test_per_class=5)
dataset=Sinusoid(10,num_tasks=1000000,
                                      transform=transform,
                                      target_transform=transform,
                                      dataset_transform=dataset_transform)

dataset2=KnobsDataset(transform=transform,
                                      target_transform=transform,
                                )

In [ ]:
meta_train_dataloader = BatchMetaDataLoader(dataset,
                                                batch_size=4,
                                                shuffle=True,
                                                num_workers=4,
                                                pin_memory=True)
meta_train_dataloader2 = DataLoader(dataset2,
                                                batch_size=4,
                                                shuffle=True,
                                                num_workers=4,
                                                pin_memory=True)

In [ ]:
for i in meta_train_dataloader:
    print(i['train'][0].shape)
    break

In [ ]:
i['train'][0]

In [3]:
from maml.custom import KnobsDataset
from torch.utils.data import  DataLoader
dataset2=KnobsDataset()
meta_train_dataloader2 = DataLoader(dataset2,
                                                batch_size=4,
                                                shuffle=True,
                                                num_workers=4,
                                                pin_memory=True)

In [4]:
for i in meta_train_dataloader2:
    print(i[0])
    print(i[1])
    break

tensor([[[ 7.7066e+02,  5.5036e+01, -2.7859e+01,  ...,  4.1404e-02,
          -1.6513e+00,  5.7893e+00],
         [ 7.7140e+02, -6.5880e+01, -7.4402e-01,  ..., -3.9855e+00,
          -2.4731e+00, -1.4246e+00],
         [ 7.7086e+02,  3.1346e+01, -5.2817e+01,  ...,  9.9167e-01,
           1.4072e+00, -2.7012e-01],
         ...,
         [ 7.7099e+02, -4.6472e+01, -2.6638e+01,  ...,  5.1776e-01,
          -5.7748e+00,  2.6094e+00],
         [-7.2919e+02,  1.3769e+01, -4.6121e+01,  ..., -4.0464e+00,
          -3.5480e+00,  3.0809e+00],
         [-2.1684e+02, -3.3143e+01,  7.2819e+01,  ..., -5.0666e+00,
           2.5418e+00,  2.9596e+00]],

        [[-7.4693e+01,  6.4475e+00,  1.9048e+01,  ..., -2.3660e+00,
          -2.3003e+00, -7.3380e+00],
         [-5.8654e+02,  2.5917e+01,  4.4982e+01,  ..., -7.2039e-01,
          -7.9784e+00,  2.8820e+00],
         [-5.8839e+02, -6.3577e+01,  4.6451e+00,  ...,  2.0003e+00,
          -6.5157e+00,  3.4679e+00],
         ...,
         [-5.8762e+02, -3

In [5]:
i[0].shape

torch.Size([4, 100, 25])

In [ ]:
i[0].shape

In [ ]:
i[1].shape

In [31]:
from torchmeta.datasets.helpers import omniglot
from torchmeta.utils.data import BatchMetaDataLoader
import matplotlib.pyplot as plt
import torch.nn.functional as F
from collections import namedtuple
from torchmeta.datasets import Omniglot, MiniImagenet
from torchmeta.toy import Sinusoid
from torchmeta.transforms import ClassSplitter, Categorical, Rotation
from torchvision.transforms import ToTensor, Resize, Compose
from maml.model import ModelConvOmniglot, ModelConvMiniImagenet, ModelMLPSinusoid
from maml.utils import ToTensor1D
import torchvision.transforms as transforms


transform = Compose([Resize(28), ToTensor()])
dataset_transform = ClassSplitter(shuffle=True,
                                      num_train_per_class=7,
                                      num_test_per_class=3)
dataset = Omniglot("data", transform=transform,
                                      target_transform=Categorical(5),
                                      num_classes_per_task=5,
                                      meta_train=True,
                                      dataset_transform=dataset_transform,
                                      download=True)
dataloader = BatchMetaDataLoader(dataset, batch_size=2, num_workers=4)

for batch in dataloader:
    train_inputs, train_targets = batch["train"]
    print('Train inputs shape: {0}'.format(train_inputs.shape))    # (16, 25, 1, 28, 28)
    print('Train targets shape: {0}'.format(train_targets.shape))  # (16, 25)

    test_inputs, test_targets = batch["test"]
    print('Test inputs shape: {0}'.format(test_inputs.shape))      # (16, 75, 1, 28, 28)
    print('Test targets shape: {0}'.format(test_targets.shape))    # (16, 75)
    for outer in train_targets:
        print(outer)
        #for inner in outer:
            #print(inner)
#             plt.imshow(transforms.ToPILImage()(outer[10]))
#             plt.show()
        break
        print('exit')
    for outer in test_targets:
        print(outer)
#         for inner in outer:
#             plt.imshow(transforms.ToPILImage()(outer[10]))
#             plt.show()
        break
        print('exit')
    break

Train inputs shape: torch.Size([2, 35, 1, 28, 28])
Train targets shape: torch.Size([2, 35])
Test inputs shape: torch.Size([2, 15, 1, 28, 28])
Test targets shape: torch.Size([2, 15])
tensor([0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2,
        2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 4, 4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1])
